---
- hosts: all

  become: yes
  become_user: root

  tasks:
    - name: APT Package Updater
      apt: 
        update_cache: yes
      become: yes
    - name: APT Package Updgrader
      apt: 
        upgrade: yes
      become: yes
